[A]
cmd = 'kitty'
args = ['--title', 'Pulsemixer (floating)', 'pulsemixer']

[R]
cmd = 'kitty'
args = ['--title', 'Ranger (floating)', 'ranger', '{{ env "HOME" }}/Docs']

[M]
cmd = 'kitty'
args = ['--title', 'Aerc (floating)', 'aerc']
