# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: "en"
dictionaryDefinitions:
  - "name": "hyperupcall"
    "path": "~/.devhidden/dictionaries/dictionary-hyperupcall.txt"
    "addWords": true
  - "name": "My Bash"
    "path": "~/.devhidden/dictionaries/dictionary-bash.txt"
  - "name": "My Linux"
    "path": "~/.devhidden/dictionaries/dictionary-linux.txt"
    "addWords": true
  - "name": "My CSS"
    "path": "~/.devhidden/dictionaries/dictionary-css.txt"
    "addWords": true
  - name: 'Comp Sci'
    path: '~/.devhidden/dictionaries/dictionary-compsci.txt'
    addWords: true
  - name: 'General'
    path: '~/.devhidden/dictionaries/dictionary-general.txt'
    addWords: true
  - name: 'Names'
    path: '~/.devhidden/dictionaries/dictionary-names.txt'
    addWords: true
dictionaries:
  - "hyperupcall"
  - 'Comp Sci'
  - 'General'
  - 'Names'
  - 'bash'
  - "My Bash"
  - 'My Linux'
  - 'css'
  - 'My CSS'
  - 'python'
  - 'win32'
  - 'latex'
  - 'makefile'
  - 'lua'
  - 'html'
  - 'data-science'
  - 'node'
  - 'npm'
  - shell'
  - 'typescript'
# Paths are relative to the ".cspell.yaml" file.
ignorePaths:
  - "**/target/"
  - "**/vendor/"
  - "**/config/formatter"
  - '**/pnpm-lock.yaml'
  - '**/docs/_site'
  - '**/bake'
  - '**/vendor'
  - '**/build'
  - '**/node_modules'
  - '**/static'
  - '**/dist'
  - '**/go.mod'
  - '**/go.sum'
  # TODO: deal with
  - '**/stars/README.md'
  - '**/data/{dates,pull_requests,commits,repositories}.json'
  - '**/hyperupcall/contributions.md'
  - '**/webext-hyperupcall'
  - '**/edwinkofler.com/content/pages/test'
  - '**/anki-plugins'
  - '**/contributing-to/'
  - '**/maintaining/schemastore'
ignoreWords:
  - kbash
  - kpolyglot
  - FiloSottile
  - kgitstatus
