line_ending: 'lf'
doublestar: true
gitignore_excludes: false
exclude:
   - "**/.data/**"
   - '**/node_modules/**'
   - '**/target/**'
formatter:
   type: 'basic'
   indent: 2
   include_document_start: false
   retain_line_breaks_single: true
   disallow_anchors: false
   indentless_arrays: true
   trim_trailing_whitespace: true
   eof_newline: true
   force_quote_style: "single"
