# shellcheck shell=bash

task.init() {
	git config set --local filter.npmrc-clean.clean './os-unix/config-language/.config/npm/npmrc-clean.sh'
	git config set --local filter.oscrc-clean.clean './os-unix/config-tools/.config/osc/oscrc-clean.sh'
}

task.build() {
	if grep -IPr '/home/(?!linuxbrew|user)' ./os-*/ | grep -Ev '(#|//|") lint-ignore'; then
		bake.die "Expected to find no '/home/* strings'"
	fi
	if grep -IPr 'vim:' ./os-*/ | grep -Ev '(#|//|") lint-ignore'; then
		bake.die "Expected to find no 'vim:' strings"
	fi
	cd "./os-unix/config-linux-rice/.config/X11/resources" || exit
	printf '%s\n' "! GENERATED BY 'bake build'" > uxterm.Xresources
	sed 's/XTerm/UXTerm/g' xterm.Xresources >> uxterm.Xresources
}

task.lint() {
	yamllint -c ./.yamllint.yaml .
}

task.test() {
	bats -p './os-unix/config-shell/.config/sh'
	./os-unix/scripts/lint-scripts.py
}

task.commit() {
	local date=
	date=$(date '+%Y.%m.%d')
	git commit -m "$date" "$@"
}
