# shellcheck shell=bash
init() {
	if [ -f ~/.dotfiles/data/setup-private.sh ]; then
		source ~/.dotfiles/data/setup-private.sh
	fi
}

task.init() {
	git config set --local filter.npmrc.clean './scripts/npmrc-clean.sh'
	git config set --local filter.oscrc.clean './scripts/oscrc-clean.sh'
	git config set --local filter.homedir.clean './scripts/homedir-clean.sh'
	git config set --local filter.npmrc.required true
	git config set --local filter.oscrc.required true
	git config set --local filter.homedir.required true
	cat > .clangd <<EOF
# DO NOT MODIFY! This file is auto-autogenerated from Bakefile.sh.
CompileFlags:
  Add: ['-DCONFIG_HOME=$HOME']
EOF
	if ! grep -q '.clangd' .git/info/exclude; then
		printf '%s\n' '.clangd' >> .git/info/exclude
	fi

	if ! mise trust --cd ~/.dotfiles --show mise | grep -q '~/.dotfiles: trusted'; then
		if ! output=$(mise trust ~/.dotfiles/.mise.toml 2>&1); then
			printf '%s\n' "$output"
		fi
	fi
	if [ ! -f ./.git/info/lefthook.checksum ]; then
		lefthook install
	fi
}

task.build() {
	./scripts/lint-scripts.py --internal-test-regex

	err=0
	while read -r file; do
		if grep -q ' _setup ' "$file" && grep -q '^main()' "$file"; then
			printf 'Should not call _setup but define main(): %s\n' "$file"
			err=1
		fi

		if grep -q ' _setup ' "$file" && ! grep -q '^installed' "$file"; then
			printf 'If calls _setup, must define installed(): %s\n' "$file"
			err=1
		fi
	done < <(find . \( -name '*.sh' -not -name 'Bakefile.sh' \) -type f)

	# Should have proper ordering of functions.
	~/.dotfiles/.data/binexec/node --input-type=module <<'EOF'
	import { readFileSync } from 'fs'
	import { glob } from 'fs/promises'

	const EXPECTED_ORDER = [
		'install.any',
		'install.debian',
		'install.ubuntu',
		'install.fedora',
		'install.opensuse',
		'install.arch',
		'installed',
		'configure',
		'caveats',
	]

	let err = 0

	for await (const file of glob('**/*.sh', { exclude: (p) => p === '.data' || p === 'vendor' })) {
		const lines = readFileSync(file, 'utf8').split('\n')

		if (!lines.some(l => l.includes('_setup '))) continue

		const order = []
		for (const line of lines) {
			for (const name of EXPECTED_ORDER) {
				if (line.startsWith(name + '(')) order.push(name)
			}
		}

		for (let i = 0; i < order.length; i++) {
			for (let j = i + 1; j < order.length; j++) {
				const pi = EXPECTED_ORDER.indexOf(order[i])
				const pj = EXPECTED_ORDER.indexOf(order[j])
				if (pi > pj) {
					console.log(`Bad ordering in ${file}: ${order[j]}() must be before ${order[i]}()`)
					err = 1
				}
			}
		}
	}
	process.exit(err)
EOF

	# grep '-P' not compatible with with multiple arguments using '-e'.
	for pattern in "${_private_forbidden_patterns[@]}"; do
		if grep -IPr --exclude 'setup-private.*' --exclude .clangd --exclude-dir node_modules --exclude-dir .data --exclude-dir vendor --exclude-dir target --exclude-dir .jekyll-cache --color=always "$pattern" ./ | grep -Ev '(#|//|") lint-ignore'; then
			printf 'Expected to find no matches for: %s\n' "$pattern"
			err=1
		fi
	done

	cd "./config-linux-rice/.config/X11/resources" || exit
	printf '%s\n' "! GENERATED BY 'bake build'" > uxterm.Xresources
	sed 's/XTerm/UXTerm/g' xterm.Xresources >> uxterm.Xresources

	return $err
}

task.lint() {
	yamllint -c ./.yamllint.yaml .
}

task.test() {
	bats -p './config-shell/.config/sh'
	./scripts/lint-scripts.py
}

task.commit() {
	local date=
	date=$(date '+%Y-%m-%d')
	git commit -m "$date" "$@"
}
