[Distribution]
Distribution=fedora

[Content]
Bootable=yes
Packages=
	kernel
	systemd
	dnf
	passwd
	sudo
	systemd-boot
	openssh-server
	vim-enhanced
	selinux-policy-targeted # Essential for Fedora's SELinux
	firewalld # Basic firewall management
	dracut-config-generic # Ensure a generic initramfs is built

[Output]
# Format=qcow2

[Boot]
Bootable=yes

[System]
Hostname=mkosi-fedora

[Service]
Enable=sshd.service
Start=sshd.service
