[lint]
# Disable linting rules that conflict with the formatter.
# See more: https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules.
ignore = [
	'W191',  # tab-indentation
	'E111',  # indentation-with-invalid-multiple
	'E114',  # indentation-with-invalid-multiple-comment
	'E117',  # over-indented
	'D206',  # docstring-tab-indentation
	'D300',  # triple-single-quotes
	'Q000',  # bad-quotes-inline-string
	'Q001',  # bad-quotes-multiline-string
	'Q002',  # bad-quotes-docstring
	'Q003',  # avoidable-escaped-quote
	'COM812',  # missing-trailing-comma
	'COM819',  # prohibited-trailing-comma
]

[format]
docstring-code-format = true
docstring-code-line-length = 20
quote-style = 'single'
indent-style = 'tab'
