config:
  backup: true
  banner: false
  check_version: true
  create: true
  dotpath: '~/.dotfiles/os/unix/user'
  link_dotfile_default: 'relative'
  link_on_import: 'relative'
  template_dotfile_default: false
  workdir: '~/.dotfiles/.dotdrop-workdir'

profiles:
  nullptr:
    variables:
      email: 'edwin@kofler.dev'
      home_src: './'
      cfg_src: '.config'
      state_src: '.local/state'
      data_src: '.local/share'
    dynvariables:
      home_dst: 'printf "%s\n" "$HOME"'
      cfg_dst: 'printf "%s\n" "$XDG_CONFIG_HOME"'
      state_dst: 'printf "%s\n" "$XDG_STATE_HOME"'
      data_dst: 'printf "%s\n" "$XDG_DATA_HOME"'
    import:
      - './dotdrop-include.yaml'

dotfiles:
  '.agignore':
    src: '{{@@ home_src @@}}/.agignore'
    dst: '{{@@ home_dst @@}}/.agignore'
  '.alsoftrc':
    src: '{{@@ home_src @@}}/.alsoftrc'
    dst: '{{@@ home_dst @@}}/.alsoftrc'
  '.aspell.conf':
    src: '{{@@ home_src @@}}/.aspell.conf'
    dst: '{{@@ home_dst @@}}/.aspell.conf'
  '.cpan/CPAN/MyConfig.pm':
    src: '{{@@ home_src @@}}/.cpan/CPAN/MyConfig.pm'
    dst: '{{@@ home_dst @@}}/.cpan/CPAN/MyConfig.pm'
  '.digrc':
    src: '{{@@ home_src @@}}/.digrc'
    dst: '{{@@ home_dst @@}}/.digrc'
  '.gnuplot':
    src: '{{@@ home_src @@}}/.gnuplot'
    dst: '{{@@ home_dst @@}}/.gnuplot'
  '.psqlrc':
    src: '{{@@ home_src @@}}/.psqlrc'
    dst: '{{@@ home_dst @@}}/.psqlrc'
  '.gnupg/dirmngr.conf':
    src: '{{@@ home_src @@}}/.gnupg/dirmngr.conf'
    dst: '{{@@ home_dst @@}}/.gnupg/dirmngr.conf'
  '.gnupg/gpg.conf':
    src: '{{@@ home_src @@}}/.gnupg/gpg.conf'
    dst: '{{@@ home_dst @@}}/.gnupg/gpg.conf'
  '.gnupg/gpg-agent.conf':
    src: '{{@@ home_src @@}}/.gnupg/gpg-agent.conf'
    dst: '{{@@ home_dst @@}}/.gnupg/gpg-agent.conf'
  '.hushlogin':
    src: '{{@@ home_src @@}}/.hushlogin'
    dst: '{{@@ home_dst @@}}/.hushlogin'
  'xinitrc':
    src: '{{@@ cfg_src @@}}/X11/xinitrc'
    dst: '{{@@ home_dst @@}}/.xinitrc'
  'bash_profile':
    src: '{{@@ cfg_src @@}}/bash/bash_profile.sh'
    dst: '{{@@ home_dst @@}}/.bash_profile'
  'bash_logout':
    src: '{{@@ cfg_src @@}}/bash/bash_logout.sh'
    dst: '{{@@ home_dst @@}}/.bash_logout'
  'bashrc':
    src: '{{@@ cfg_src @@}}/bash/bashrc.sh'
    dst: '{{@@ home_dst @@}}/.bashrc'
  'profile':
    src: '{{@@ cfg_src @@}}/shell/profile.sh'
    dst: '{{@@ home_dst @@}}/.profile'
  'zshenv':
    src: '{{@@ cfg_src @@}}/zsh/.zshenv'
    dst: '{{@@ home_dst @@}}/.zshenv'
  '.config/.gtktermrc':
    src: '{{@@ cfg_src @@}}/.gtktermrc'
    dst: '{{@@ cfg_dst @@}}/.gtktermrc'
  '.config/rofi-json-menu.json':
    src: '{{@@ cfg_src @@}}/rofi-json-menu.json'
    dst: '{{@@ cfg_dst @@}}/rofi-json-menu.json'
  '.config/aerc/aerc.conf':
    src: '{{@@ cfg_src @@}}/aerc/aerc.conf'
    dst: '{{@@ cfg_dst @@}}/aerc/aerc.conf'
  '.config/aerc/binds.conf':
    src: '{{@@ cfg_src @@}}/aerc/binds.conf'
    dst: '{{@@ cfg_dst @@}}/aerc/binds.conf'
  '.config/alacritty':
    src: '{{@@ cfg_src @@}}/alacritty'
    dst: '{{@@ cfg_dst @@}}/alacritty'
  '.config/albert/albert.conf':
    src: '{{@@ cfg_src @@}}/albert/albert.conf'
    dst: '{{@@ cfg_dst @@}}/albert/albert.conf'
  '.config/alsa':
    src: '{{@@ cfg_src @@}}/alsa'
    dst: '{{@@ cfg_dst @@}}/alsa'
  '.config/appimagelauncher.cfg':
    src: '{{@@ cfg_src @@}}/appimagelauncher.cfg'
    dst: '{{@@ cfg_dst @@}}/appimagelauncher.cfg'
  '.config/aria2':
    src: '{{@@ cfg_src @@}}/aria2'
    dst: '{{@@ cfg_dst @@}}/aria2'
  '.config/awesome':
    src: '{{@@ cfg_src @@}}/awesome'
    dst: '{{@@ cfg_dst @@}}/awesome'
  '.config/bash':
    src: '{{@@ cfg_src @@}}/bash'
    dst: '{{@@ cfg_dst @@}}/bash'
  '.config/bat':
    src: '{{@@ cfg_src @@}}/bat'
    dst: '{{@@ cfg_dst @@}}/bat'
  '.config/bpython':
    src: '{{@@ cfg_src @@}}/bpython'
    dst: '{{@@ cfg_dst @@}}/bpython'
  '.config/broot':
    src: '{{@@ cfg_src @@}}/broot'
    dst: '{{@@ cfg_dst @@}}/broot'
  '.config/bspwm':
    src: '{{@@ cfg_src @@}}/bspwm'
    dst: '{{@@ cfg_dst @@}}/bspwm'
  '.config/cabal/config':
    src: '{{@@ cfg_src @@}}/cabal/config'
    dst: '{{@@ cfg_dst @@}}/cabal/config'
  '.config/cactus':
    src: '{{@@ cfg_src @@}}/cactus'
    dst: '{{@@ cfg_dst @@}}/cactus'
  '.config/calcurse':
    src: '{{@@ cfg_src @@}}/calcurse'
    dst: '{{@@ cfg_dst @@}}/calcurse'
  '.config/cargo':
    src: '{{@@ cfg_src @@}}/cargo'
    dst: '{{@@ cfg_dst @@}}/cargo'
  '.config/cava':
    src: '{{@@ cfg_src @@}}/cava'
    dst: '{{@@ cfg_dst @@}}/cava'
  '.config/ccache':
    src: '{{@@ cfg_src @@}}/ccache'
    dst: '{{@@ cfg_dst @@}}/ccache'
  '.config/cdm':
    src: '{{@@ cfg_src @@}}/cdm'
    dst: '{{@@ cfg_dst @@}}/cdm'
  '.config/choose':
    src: '{{@@ cfg_src @@}}/choose'
    dst: '{{@@ cfg_dst @@}}/choose'
  '.config/cliflix':
    src: '{{@@ cfg_src @@}}/cliflix'
    dst: '{{@@ cfg_dst @@}}/cliflix'
  '.config/conda':
    src: '{{@@ cfg_src @@}}/conda'
    dst: '{{@@ cfg_dst @@}}/conda'
  '.config/conky':
    src: '{{@@ cfg_src @@}}/conky'
    dst: '{{@@ cfg_dst @@}}/conky'
  '.config/cookiecutter':
    src: '{{@@ cfg_src @@}}/cookiecutter'
    dst: '{{@@ cfg_dst @@}}/cookiecutter'
  '.config/cmus/rc':
    src: '{{@@ cfg_src @@}}/cmus/rc'
    dst: '{{@@ cfg_dst @@}}/cmus/rc'
  '.config/Code/User/keybindings.json':
    src: '{{@@ cfg_src @@}}/Code/User/keybindings.json'
    dst: '{{@@ cfg_dst @@}}/Code/User/keybindings.json'
  '.config/Code/User/settings.json':
    src: '{{@@ cfg_src @@}}/Code/User/settings.json'
    dst: '{{@@ cfg_dst @@}}/Code/User/settings.json'
  '.config/curl':
    src: '{{@@ cfg_src @@}}/curl'
    dst: '{{@@ cfg_dst @@}}/curl'
  '.config/ddcutil':
    src: '{{@@ cfg_src @@}}/ddcutil'
    dst: '{{@@ cfg_dst @@}}/ddcutil'
  '.config/dircolors':
    src: '{{@@ cfg_src @@}}/dircolors'
    dst: '{{@@ cfg_dst @@}}/dircolors'
  '.config/discocss':
    src: '{{@@ cfg_src @@}}/discocss'
    dst: '{{@@ cfg_dst @@}}/discocss'
  '.config/dotshellgen':
    src: '{{@@ cfg_src @@}}/dotshellgen'
    dst: '{{@@ cfg_dst @@}}/dotshellgen'
  '.config/dunst':
    src: '{{@@ cfg_src @@}}/dunst'
    dst: '{{@@ cfg_dst @@}}/dunst'
  '.config/dxhd':
    src: '{{@@ cfg_src @@}}/dxhd'
    dst: '{{@@ cfg_dst @@}}/dxhd'
  '.config/emptty':
    src: '{{@@ cfg_src @@}}/emptty'
    dst: '{{@@ cfg_dst @@}}/emptty'
  '.config/environment.d':
    src: '{{@@ cfg_src @@}}/environment.d'
    dst: '{{@@ cfg_dst @@}}/environment.d'
  '.config/eww':
    src: '{{@@ cfg_src @@}}/eww'
    dst: '{{@@ cfg_dst @@}}/eww'
  '.config/fish':
    src: '{{@@ cfg_src @@}}/fish'
    dst: '{{@@ cfg_dst @@}}/fish'
  '.config/fontconfig':
    src: '{{@@ cfg_src @@}}/fontconfig'
    dst: '{{@@ cfg_dst @@}}/fontconfig'
  '.config/gh/config.yml':
    src: '{{@@ cfg_src @@}}/gh/config.yml'
    dst: '{{@@ cfg_dst @@}}/gh/config.yml'
  '.config/gdb':
    src: '{{@@ cfg_src @@}}/gdb'
    dst: '{{@@ cfg_dst @@}}/gdb'
  '.config/git':
    src: '{{@@ cfg_src @@}}/git'
    dst: '{{@@ cfg_dst @@}}/git'
  '.config/glue':
    src: '{{@@ cfg_src @@}}/glue'
    dst: '{{@@ cfg_dst @@}}/glue'
  '.config/octave':
    src: '{{@@ cfg_src @@}}/octave'
    dst: '{{@@ cfg_dst @@}}/octave'
  '.config/osc':
    src: '{{@@ cfg_src @@}}/osc'
    dst: '{{@@ cfg_dst @@}}/osc'
  '.config/helix':
    src: '{{@@ cfg_src @@}}/helix'
    dst: '{{@@ cfg_dst @@}}/helix'
  '.config/hg':
    src: '{{@@ cfg_src @@}}/hg'
    dst: '{{@@ cfg_dst @@}}/hg'
  '.config/htop':
    src: '{{@@ cfg_src @@}}/htop'
    dst: '{{@@ cfg_dst @@}}/htop'
  '.config/i3':
    src: '{{@@ cfg_src @@}}/i3'
    dst: '{{@@ cfg_dst @@}}/i3'
  '.config/i3blocks':
    src: '{{@@ cfg_src @@}}/i3blocks'
    dst: '{{@@ cfg_dst @@}}/i3blocks'
  '.config/i3status':
    src: '{{@@ cfg_src @@}}/i3status'
    dst: '{{@@ cfg_dst @@}}/i3status'
  '.config/info':
    src: '{{@@ cfg_src @@}}/info'
    dst: '{{@@ cfg_dst @@}}/info'
  '.config/ion':
    src: '{{@@ cfg_src @@}}/ion'
    dst: '{{@@ cfg_dst @@}}/ion'
  '.config/irb':
    src: '{{@@ cfg_src @@}}/irb'
    dst: '{{@@ cfg_dst @@}}/irb'
  '.config/irssi':
    src: '{{@@ cfg_src @@}}/irssi'
    dst: '{{@@ cfg_dst @@}}/irssi'
  '.config/kak':
    src: '{{@@ cfg_src @@}}/kak'
    dst: '{{@@ cfg_dst @@}}/kak'
  '.config/quasipanacea':
    src: '{{@@ cfg_src @@}}/quasipanacea'
    dst: '{{@@ cfg_dst @@}}/quasipanacea'
  '.config/kermit':
    src: '{{@@ cfg_src @@}}/kermit'
    dst: '{{@@ cfg_dst @@}}/kermit'
  '.config/kitty':
    src: '{{@@ cfg_src @@}}/kitty'
    dst: '{{@@ cfg_dst @@}}/kitty'
  '.config/lazydocker':
    src: '{{@@ cfg_src @@}}/lazydocker'
    dst: '{{@@ cfg_dst @@}}/lazydocker'
  '.config/less':
    src: '{{@@ cfg_src @@}}/less'
    dst: '{{@@ cfg_dst @@}}/less'
  '.config/libfsguest':
    src: '{{@@ cfg_src @@}}/libfsguest'
    dst: '{{@@ cfg_dst @@}}/libfsguest'
  '.config/liquidprompt':
    src: '{{@@ cfg_src @@}}/liquidprompt'
    dst: '{{@@ cfg_dst @@}}/liquidprompt'
  '.config/llpp.conf':
    src: '{{@@ cfg_src @@}}/llpp.conf'
    dst: '{{@@ cfg_dst @@}}/llpp.conf'
  '.config/ltrace':
    src: '{{@@ cfg_src @@}}/ltrace'
    dst: '{{@@ cfg_dst @@}}/ltrace'
  '.config/ly':
    src: '{{@@ cfg_src @@}}/ly'
    dst: '{{@@ cfg_dst @@}}/ly'
  '.config/maven':
    src: '{{@@ cfg_src @@}}/maven'
    dst: '{{@@ cfg_dst @@}}/maven'
  '.config/micro/bindings.json':
    src: '{{@@ cfg_src @@}}/micro/bindings.json'
    dst: '{{@@ cfg_dst @@}}/micro/bindings.json'
  '.config/micro/settings.json':
    src: '{{@@ cfg_src @@}}/micro/settings.json'
    dst: '{{@@ cfg_dst @@}}/micro/settings.json'
  '.config/mnemosyne/config.py':
    src: '{{@@ cfg_src @@}}/mnemosyne/config.py'
    dst: '{{@@ cfg_dst @@}}/mnemosyne/config.py'
  '.config/most':
    src: '{{@@ cfg_src @@}}/most'
    dst: '{{@@ cfg_dst @@}}/most'
  '.config/mpd':
    src: '{{@@ cfg_src @@}}/mpd'
    dst: '{{@@ cfg_dst @@}}/mpd'
  '.config/mpv':
    src: '{{@@ cfg_src @@}}/mpv'
    dst: '{{@@ cfg_dst @@}}/mpv'
  '.config/namur':
    src: '{{@@ cfg_src @@}}/namur'
    dst: '{{@@ cfg_dst @@}}/namur'
  '.config/nano':
    src: '{{@@ cfg_src @@}}/nano'
    dst: '{{@@ cfg_dst @@}}/nano'
  '.config/nb':
    src: '{{@@ cfg_src @@}}/nb'
    dst: '{{@@ cfg_dst @@}}/nb'
  '.config/ncmpcpp':
    src: '{{@@ cfg_src @@}}/ncmpcpp'
    dst: '{{@@ cfg_dst @@}}/ncmpcpp'
  '.config/ncpamixer.conf':
    src: '{{@@ cfg_src @@}}/ncpamixer.conf'
    dst: '{{@@ cfg_dst @@}}/ncpamixer.conf'
  '.config/neofetch':
    src: '{{@@ cfg_src @@}}/neofetch'
    dst: '{{@@ cfg_dst @@}}/neofetch'
  '.config/neomutt':
    src: '{{@@ cfg_src @@}}/neomutt'
    dst: '{{@@ cfg_dst @@}}/neomutt'
  '.config/nimble':
    src: '{{@@ cfg_src @@}}/nimble'
    dst: '{{@@ cfg_dst @@}}/nimble'
  '.config/nitrogen':
    src: '{{@@ cfg_src @@}}/nitrogen'
    dst: '{{@@ cfg_dst @@}}/nitrogen'
  '.config/notmuch':
    src: '{{@@ cfg_src @@}}/notmuch'
    dst: '{{@@ cfg_dst @@}}/notmuch'
  '.config/npm':
    src: '{{@@ cfg_src @@}}/npm'
    dst: '{{@@ cfg_dst @@}}/npm'
  '.config/nu':
    src: '{{@@ cfg_src @@}}/nu'
    dst: '{{@@ cfg_dst @@}}/nu'
  '.config/nvchecker':
    src: '{{@@ cfg_src @@}}/nvchecker'
    dst: '{{@@ cfg_dst @@}}/nvchecker'
  '.config/nvim':
    src: '{{@@ cfg_src @@}}/nvim'
    dst: '{{@@ cfg_dst @@}}/nvim'
  '.config/obs-studio/themes':
    src: '{{@@ cfg_src @@}}/obs-studio/themes'
    dst: '{{@@ cfg_dst @@}}/obs-studio/themes'
  '.config/openbox':
    src: '{{@@ cfg_src @@}}/openbox'
    dst: '{{@@ cfg_dst @@}}/openbox'
  '.config/OpenSCAD':
    src: '{{@@ cfg_src @@}}/OpenSCAD'
    dst: '{{@@ cfg_dst @@}}/OpenSCAD'
  '.config/ox':
    src: '{{@@ cfg_src @@}}/ox'
    dst: '{{@@ cfg_dst @@}}/ox'
  '.config/pacman':
    src: '{{@@ cfg_src @@}}/pacman'
    dst: '{{@@ cfg_dst @@}}/pacman'
  '.config/pacmixer':
    src: '{{@@ cfg_src @@}}/pacmixer'
    dst: '{{@@ cfg_dst @@}}/pacmixer'
  '.config/pamix.conf':
    src: '{{@@ cfg_src @@}}/pamix.conf'
    dst: '{{@@ cfg_dst @@}}/pamix.conf'
  '.config/paru':
    src: '{{@@ cfg_src @@}}/paru'
    dst: '{{@@ cfg_dst @@}}/paru'
  '.config/pavucontrol.ini':
    src: '{{@@ cfg_src @@}}/pavucontrol.ini'
    dst: '{{@@ cfg_dst @@}}/pavucontrol.ini'
  '.config/pgcli':
    src: '{{@@ cfg_src @@}}/pgcli'
    dst: '{{@@ cfg_dst @@}}/pgcli'
  '.config/picom':
    src: '{{@@ cfg_src @@}}/picom'
    dst: '{{@@ cfg_dst @@}}/picom'
  '.config/pijul':
    src: '{{@@ cfg_src @@}}/pijul'
    dst: '{{@@ cfg_dst @@}}/pijul'
  '.config/please':
    src: '{{@@ cfg_src @@}}/please'
    dst: '{{@@ cfg_dst @@}}/please'
  '.config/polybar':
    src: '{{@@ cfg_src @@}}/polybar'
    dst: '{{@@ cfg_dst @@}}/polybar'
  '.config/powerline':
    src: '{{@@ cfg_src @@}}/powerline'
    dst: '{{@@ cfg_dst @@}}/powerline'
  '.config/pudb':
    src: '{{@@ cfg_src @@}}/pudb'
    dst: '{{@@ cfg_dst @@}}/pudb'
  '.config/pulse/client.conf':
    src: '{{@@ cfg_src @@}}/pulse/client.conf'
    dst: '{{@@ cfg_dst @@}}/pulse/client.conf'
  '.config/pulsemixer.cfg':
    src: '{{@@ cfg_src @@}}/pulsemixer.cfg'
    dst: '{{@@ cfg_dst @@}}/pulsemixer.cfg'
  '.config/pylint':
    src: '{{@@ cfg_src @@}}/pylint'
    dst: '{{@@ cfg_dst @@}}/pylint'
  '.config/pypoetry':
    src: '{{@@ cfg_src @@}}/pypoetry'
    dst: '{{@@ cfg_dst @@}}/pypoetry'
  '.config/python':
    src: '{{@@ cfg_src @@}}/python'
    dst: '{{@@ cfg_dst @@}}/python'
  '.config/quark':
    src: '{{@@ cfg_src @@}}/quark'
    dst: '{{@@ cfg_dst @@}}/quark'
  '.config/ranger':
    src: '{{@@ cfg_src @@}}/ranger'
    dst: '{{@@ cfg_dst @@}}/ranger'
  '.config/readline':
    src: '{{@@ cfg_src @@}}/readline'
    dst: '{{@@ cfg_dst @@}}/readline'
  '.config/redshift':
    src: '{{@@ cfg_src @@}}/redshift'
    dst: '{{@@ cfg_dst @@}}/redshift'
  '.config/repoctl':
    src: '{{@@ cfg_src @@}}/repoctl'
    dst: '{{@@ cfg_dst @@}}/repoctl'
  '.config/ripgrep':
    src: '{{@@ cfg_src @@}}/ripgrep'
    dst: '{{@@ cfg_dst @@}}/ripgrep'
  '.config/rofi':
    src: '{{@@ cfg_src @@}}/rofi'
    dst: '{{@@ cfg_dst @@}}/rofi'
  '.config/rtorrent':
    src: '{{@@ cfg_src @@}}/rtorrent'
    dst: '{{@@ cfg_dst @@}}/rtorrent'
  '.config/salamis':
    src: '{{@@ cfg_src @@}}/salamis'
    dst: '{{@@ cfg_dst @@}}/salamis'
  '.config/sheldon':
    src: '{{@@ cfg_src @@}}/sheldon'
    dst: '{{@@ cfg_dst @@}}/sheldon'
  '.config/shell':
    src: '{{@@ cfg_src @@}}/shell'
    dst: '{{@@ cfg_dst @@}}/shell'
  '.config/slack-term':
    src: '{{@@ cfg_src @@}}/slack-term'
    dst: '{{@@ cfg_dst @@}}/slack-term'
  '.config/starship':
    src: '{{@@ cfg_src @@}}/starship'
    dst: '{{@@ cfg_dst @@}}/starship'
  '.config/sticker-selector':
    src: '{{@@ cfg_src @@}}/sticker-selector'
    dst: '{{@@ cfg_dst @@}}/sticker-selector'
  '.config/sublime-text-3/Packages/User/Preferences.sublime-settings':
    src: '{{@@ cfg_src @@}}/sublime-text-3/Packages/User/Preferences.sublime-settings'
    dst: '{{@@ cfg_dst @@}}/sublime-text-3/Packages/User/Preferences.sublime-settings'
  '.config/sublime-text-3/Packages/User/Package Control.sublime-settings':
    src: '{{@@ cfg_src @@}}/sublime-text-3/Packages/User/Package Control.sublime-settings'
    dst: '{{@@ cfg_dst @@}}/sublime-text-3/Packages/User/Package Control.sublime-settings'
  '.config/sx':
    src: '{{@@ cfg_src @@}}/sx'
    dst: '{{@@ cfg_dst @@}}/sx'
  '.config/sxhkd':
    src: '{{@@ cfg_src @@}}/sxhkd'
    dst: '{{@@ cfg_dst @@}}/sxhkd'
  '.config/swaylock':
    src: '{{@@ cfg_src @@}}/swaylock'
    dst: '{{@@ cfg_dst @@}}/swaylock'
  '.config/taffybar':
    src: '{{@@ cfg_src @@}}/taffybar'
    dst: '{{@@ cfg_dst @@}}/taffybar'
  '.config/taskwarrior':
    src: '{{@@ cfg_src @@}}/taskwarrior'
    dst: '{{@@ cfg_dst @@}}/taskwarrior'
  '.config/terminator':
    src: '{{@@ cfg_src @@}}/terminator'
    dst: '{{@@ cfg_dst @@}}/terminator'
  '.config/termite':
    src: '{{@@ cfg_src @@}}/termite'
    dst: '{{@@ cfg_dst @@}}/termite'
  '.config/tig':
    src: '{{@@ cfg_src @@}}/tig'
    dst: '{{@@ cfg_dst @@}}/tig'
  '.config/tmux':
    src: '{{@@ cfg_src @@}}/tmux'
    dst: '{{@@ cfg_dst @@}}/tmux'
  '.config/toast':
    src: '{{@@ cfg_src @@}}/toast'
    dst: '{{@@ cfg_dst @@}}/toast'
  '.config/twmn':
    src: '{{@@ cfg_src @@}}/twmn'
    dst: '{{@@ cfg_dst @@}}/twmn'
  '.config/udiskie':
    src: '{{@@ cfg_src @@}}/udiskie'
    dst: '{{@@ cfg_dst @@}}/udiskie'
  '.config/urlwatch':
    src: '{{@@ cfg_src @@}}/urlwatch'
    dst: '{{@@ cfg_dst @@}}/urlwatch'
  '.config/urxvt':
    src: '{{@@ cfg_src @@}}/urxvt'
    dst: '{{@@ cfg_dst @@}}/urxvt'
  '.config/viewnior':
    src: '{{@@ cfg_src @@}}/viewnior'
    dst: '{{@@ cfg_dst @@}}/viewnior'
  '.config/vim':
    src: '{{@@ cfg_src @@}}/vim'
    dst: '{{@@ cfg_dst @@}}/vim'
  '.config/wget':
    src: '{{@@ cfg_src @@}}/wget'
    dst: '{{@@ cfg_dst @@}}/wget'
  '.config/wtf':
    src: '{{@@ cfg_src @@}}/wtf'
    dst: '{{@@ cfg_dst @@}}/wtf'
  '.config/xbindkeys':
    src: '{{@@ cfg_src @@}}/xbindkeys'
    dst: '{{@@ cfg_dst @@}}/xbindkeys'
  '.config/X11':
    src: '{{@@ cfg_src @@}}/X11'
    dst: '{{@@ cfg_dst @@}}/X11'
  '.config/xkb':
    src: '{{@@ cfg_src @@}}/xkb'
    dst: '{{@@ cfg_dst @@}}/xkb'
  '.config/xmobar':
    src: '{{@@ cfg_src @@}}/xmobar'
    dst: '{{@@ cfg_dst @@}}/xmobar'
  '.config/xob':
    src: '{{@@ cfg_src @@}}/xob'
    dst: '{{@@ cfg_dst @@}}/xob'
  '.config/xplr':
    src: '{{@@ cfg_src @@}}/xplr'
    dst: '{{@@ cfg_dst @@}}/xplr'
  '.config/yapf':
    src: '{{@@ cfg_src @@}}/yapf'
    dst: '{{@@ cfg_dst @@}}/yapf'
  '.config/yay':
    src: '{{@@ cfg_src @@}}/yay'
    dst: '{{@@ cfg_dst @@}}/yay'
  '.config/youtube-dl':
    src: '{{@@ cfg_src @@}}/youtube-dl'
    dst: '{{@@ cfg_dst @@}}/youtube-dl'
  '.config/zathura':
    src: '{{@@ cfg_src @@}}/zathura'
    dst: '{{@@ cfg_dst @@}}/zathura'
  '.config/zsh':
    src: '{{@@ cfg_src @@}}/zsh'
    dst: '{{@@ cfg_dst @@}}/zsh'
  '.local/share/applications/FoxBlender.desktop':
    src: '{{@@ data_src @@}}/applications/FoxBlender.desktop'
    dst: '{{@@ data_dst @@}}/applications/FoxBlender.desktop'
  '.local/share/sdkman/etc/config':
    src: '{{@@ data_src @@}}/sdkman/etc/config'
    dst: '{{@@ data_dst @@}}/sdkman/etc/config'
  '.local/state/dotshellgen':
    src: '{{@@ state_src @@}}/dotshellgen'
    dst: '{{@@ state_dst @@}}/dotshellgen'
  'pam':
    src: '{{@@ home_src @@}}/.pam_environment/xdg-default.conf'
    dst: '{{@@ home_dst @@}}/.pam_environment'
