dotfiles:
  - '.agignore'
  - '.alsoftrc'
  - '.aspell.conf'
  - '.cpan/CPAN/MyConfig.pm'
  - '.digrc'
  - '.gnuplot'
  - '.psqlrc'
  - '.gnupg/dirmngr.conf'
  - '.gnupg/gpg.conf'
  - '.gnupg/gpg-agent.conf'
  - '.hushlogin'
  - 'xinitrc'
  - 'bash_profile'
  - 'bash_logout'
  - 'bashrc'
  - 'profile'
  - 'zshenv'
  - '.config/.gtktermrc'
  - '.config/rofi-json-menu.json'
  - '.config/aerc/aerc.conf'
  - '.config/aerc/binds.conf'
  - '.config/alacritty'
  - '.config/albert/albert.conf'
  - '.config/alsa'
  - '.config/appimagelauncher.cfg'
  - '.config/aria2'
  - '.config/awesome'
  - '.config/bash'
  - '.config/bat'
  - '.config/bpython'
  - '.config/broot'
  - '.config/bspwm'
  - '.config/cabal/config'
  - '.config/cactus'
  - '.config/calcurse'
  - '.config/cargo'
  - '.config/cava'
  - '.config/ccache'
  - '.config/cdm'
  - '.config/choose'
  - '.config/cliflix'
  - '.config/conda'
  - '.config/conky'
  - '.config/cookiecutter'
  - '.config/cmus/rc'
  - '.config/Code/User/keybindings.json'
  - '.config/Code/User/settings.json'
  - '.config/curl'
  - '.config/ddcutil'
  - '.config/dircolors'
  - '.config/discocss'
  - '.config/dotshellgen'
  - '.config/dunst'
  - '.config/dxhd'
  - '.config/emptty'
  - '.config/environment.d'
  - '.config/eww'
  - '.config/fish'
  - '.config/fontconfig'
  - '.config/gh/config.yml'
  - '.config/gdb'
  - '.config/git'
  - '.config/glue'
  - '.config/octave'
  - '.config/osc'
  - '.config/helix'
  - '.config/hg'
  - '.config/htop'
  - '.config/i3'
  - '.config/i3blocks'
  - '.config/i3status'
  - '.config/info'
  - '.config/ion'
  - '.config/irb'
  - '.config/irssi'
  - '.config/kak'
  - '.config/quasipanacea'
  - '.config/kermit'
  - '.config/kitty'
  - '.config/lazydocker'
  - '.config/less'
  - '.config/libfsguest'
  - '.config/liquidprompt'
  - '.config/llpp.conf'
  - '.config/ltrace'
  - '.config/ly'
  - '.config/maven'
  - '.config/micro/bindings.json'
  - '.config/micro/settings.json'
  - '.config/mnemosyne/config.py'
  - '.config/most'
  - '.config/mpd'
  - '.config/mpv'
  - '.config/namur'
  - '.config/nano'
  - '.config/nb'
  - '.config/ncmpcpp'
  - '.config/ncpamixer.conf'
  - '.config/neofetch'
  - '.config/neomutt'
  - '.config/nimble'
  - '.config/nitrogen'
  - '.config/notmuch'
  - '.config/npm'
  - '.config/nu'
  - '.config/nvchecker'
  - '.config/nvim'
  - '.config/obs-studio/themes'
  - '.config/openbox'
  - '.config/OpenSCAD'
  - '.config/ox'
  - '.config/pacman'
  - '.config/pacmixer'
  - '.config/pamix.conf'
  - '.config/paru'
  - '.config/pavucontrol.ini'
  - '.config/pgcli'
  - '.config/picom'
  - '.config/pijul'
  - '.config/please'
  - '.config/polybar'
  - '.config/powerline'
  - '.config/pudb'
  - '.config/pulse/client.conf'
  - '.config/pulsemixer.cfg'
  - '.config/pylint'
  - '.config/pypoetry'
  - '.config/python'
  - '.config/quark'
  - '.config/ranger'
  - '.config/readline'
  - '.config/redshift'
  - '.config/repoctl'
  - '.config/ripgrep'
  - '.config/rofi'
  - '.config/rtorrent'
  - '.config/salamis'
  - '.config/sheldon'
  - '.config/shell'
  - '.config/slack-term'
  - '.config/starship'
  - '.config/sticker-selector'
  - '.config/sublime-text-3/Packages/User/Preferences.sublime-settings'
  - '.config/sublime-text-3/Packages/User/Package Control.sublime-settings'
  - '.config/sx'
  - '.config/sxhkd'
  - '.config/swaylock'
  - '.config/taffybar'
  - '.config/taskwarrior'
  - '.config/terminator'
  - '.config/termite'
  - '.config/tig'
  - '.config/tmux'
  - '.config/toast'
  - '.config/twmn'
  - '.config/udiskie'
  - '.config/urlwatch'
  - '.config/urxvt'
  - '.config/viewnior'
  - '.config/vim'
  - '.config/wget'
  - '.config/wtf'
  - '.config/xbindkeys'
  - '.config/X11'
  - '.config/xkb'
  - '.config/xmobar'
  - '.config/xob'
  - '.config/xplr'
  - '.config/yapf'
  - '.config/yay'
  - '.config/youtube-dl'
  - '.config/zathura'
  - '.config/zsh'
  - '.local/share/applications/FoxBlender.desktop'
  - '.local/share/sdkman/etc/config'
  - '.local/state/dotshellgen'
  - 'pam'
