dotfiles:
  - '.agignore'
  - '.alsoftrc'
  - '.aspell.conf'
  - '.cpan__CPAN__MyConfig.pm'
  - '.digrc'
  - '.gnuplot'
  - '.psqlrc'
  - '.gnupg__dirmngr.conf'
  - '.gnupg__gpg.conf'
  - '.gnupg__gpg-agent.conf'
  - '.hushlogin'
  - 'xinitrc'
  - 'bash_profile'
  - 'bash_logout'
  - 'bashrc'
  - 'profile'
  - 'zshenv'
  - '.config__.gtktermrc'
  - '.config__rofi-json-menu.json'
  - '.config__aerc__aerc.conf'
  - '.config__aerc__binds.conf'
  - '.config__alacritty'
  - '.config__albert__albert.conf'
  - '.config__alsa'
  - '.config__appimagelauncher.cfg'
  - '.config__aria2'
  - '.config__awesome'
  - '.config__bash'
  - '.config__bat'
  - '.config__bpython'
  - '.config__broot'
  - '.config__bspwm'
  - '.config__cabal__config'
  - '.config__cactus'
  - '.config__calcurse'
  - '.config__cargo'
  - '.config__cava'
  - '.config__ccache'
  - '.config__cdm'
  - '.config__choose'
  - '.config__cliflix'
  - '.config__conda'
  - '.config__conky'
  - '.config__cookiecutter'
  - '.config__cmus__rc'
  - '.config__Code__User__keybindings.json'
  - '.config__Code__User__settings.json'
  - '.config__curl'
  - '.config__ddcutil'
  - '.config__dircolors'
  - '.config__discocss'
  - '.config__dotshellgen'
  - '.config__dunst'
  - '.config__dxhd'
  - '.config__emptty'
  - '.config__environment.d'
  - '.config__eww'
  - '.config__fish'
  - '.config__fontconfig'
  - '.config__gh__config.yml'
  - '.config__gdb'
  - '.config__git'
  - '.config__glue'
  - '.config__octave'
  - '.config__osc'
  - '.config__helix'
  - '.config__hg'
  - '.config__htop'
  - '.config__i3'
  - '.config__i3blocks'
  - '.config__i3status'
  - '.config__info'
  - '.config__ion'
  - '.config__irb'
  - '.config__irssi'
  - '.config__kak'
  - '.config__quasipanacea'
  - '.config__kermit'
  - '.config__kitty'
  - '.config__lazydocker'
  - '.config__less'
  - '.config__libfsguest'
  - '.config__liquidprompt'
  - '.config__llpp.conf'
  - '.config__ltrace'
  - '.config__ly'
  - '.config__maven'
  - '.config__micro__bindings.json'
  - '.config__micro__settings.json'
  - '.config__mnemosyne__config.py'
  - '.config__most'
  - '.config__mpd'
  - '.config__mpv'
  - '.config__namur'
  - '.config__nano'
  - '.config__nb'
  - '.config__ncmpcpp'
  - '.config__ncpamixer.conf'
  - '.config__neofetch'
  - '.config__nimble'
  - '.config__nitrogen'
  - '.config__notmuch'
  - '.config__npm'
  - '.config__nu'
  - '.config__nvchecker'
  - '.config__nvim'
  - '.config__obs-studio__themes'
  - '.config__openbox'
  - '.config__OpenSCAD'
  - '.config__ox'
  - '.config__pacman'
  - '.config__pacmixer'
  - '.config__pamix.conf'
  - '.config__paru'
  - '.config__pavucontrol.ini'
  - '.config__pgcli'
  - '.config__picom'
  - '.config__pijul'
  - '.config__please'
  - '.config__polybar'
  - '.config__powerline'
  - '.config__pudb'
  - '.config__pulse__client.conf'
  - '.config__pulsemixer.cfg'
  - '.config__pylint'
  - '.config__pypoetry'
  - '.config__python'
  - '.config__quark'
  - '.config__ranger'
  - '.config__readline'
  - '.config__redshift'
  - '.config__repoctl'
  - '.config__ripgrep'
  - '.config__rofi'
  - '.config__rtorrent'
  - '.config__salamis'
  - '.config__sheldon'
  - '.config__shell'
  - '.config__slack-term'
  - '.config__starship'
  - '.config__sticker-selector'
  - '.config__sublime-text-3__Packages__User__Preferences.sublime-settings'
  - '.config__sublime-text-3__Packages__User__Package Control.sublime-settings'
  - '.config__sx'
  - '.config__sxhkd'
  - '.config__swaylock'
  - '.config__taffybar'
  - '.config__taskwarrior'
  - '.config__terminator'
  - '.config__termite'
  - '.config__tig'
  - '.config__tmux'
  - '.config__toast'
  - '.config__twmn'
  - '.config__udiskie'
  - '.config__urlwatch'
  - '.config__urxvt'
  - '.config__viewnior'
  - '.config__vim'
  - '.config__wget'
  - '.config__wtf'
  - '.config__xbindkeys'
  - '.config__X11'
  - '.config__xkb'
  - '.config__xmobar'
  - '.config__xob'
  - '.config__xplr'
  - '.config__yapf'
  - '.config__yay'
  - '.config__youtube-dl'
  - '.config__zathura'
  - '.config__zsh'
  - '.local__share__applications__FoxBlender.desktop'
  - '.local__share__sdkman__etc__config'
  - '.local__state__dotshellgen'
  - 'pam'
