---
- name: 'Add VSCode'
  vars:
    keyfile: '/etc/apt/keyrings/microsoft.gpg'
    filename: 'vscode'
  block:
    - name: 'Add Microsoft GPG Key'
      ansible.builtin.get_url:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        dest: '{{ keyfile }}'
      become: true
    - name: 'Add VSCode Repository'
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64,arm64,armhf signed-by={{ keyfile }}] https://packages.microsoft.com/repos/code stable main'
        filename: '{{ filename }}'
        state: 'present'
      become: true
    # - name: 'Add VSCode Repository'
    #   ansible.builtin.yum_repository:
    #     name: 'code'
    #     description: 'Visual Studio Code'
    #     baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
    #     enabled: yes
    #     gpgcheck: yes
    #     gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
    #     file: '{{ filename }}'
    #     state: 'present'
    #   become: true
    #   when: 
    - name: 'Install VSCode and VSCode Insiders'
      ansible.builtin.package:
        name: 'vscode vscode-insiders'
        state: 'present'
