; https://github.com/git/git/tree/master/contrib/diff-highlight
[pager]
	log =  /usr/share/doc/git/contrib/diff-highlight/diff-highlight | less
	show = /usr/share/doc/git/contrib/diff-highlight/diff-highlight | less
	diff = /usr/share/doc/git/contrib/diff-highlight/diff-highlight | less

[interactive]
    diffFilter = diff-highlight
