#!/usr/bin/env bash

# Bash is the most featureful lowest common denominator in shells
# on Unix machines. We extract bash intrinsics with the '# clone(...)'
# annotations such that funtions, aliases, and readline declarations
# can be shared more easily across *nix machines


# ------------------- Utility Functions ------------------ #
util_print_autogen_info() {
	cat <<-EOF
	# shellcheck shell=bash
	# Autogenerated from $(basename "$0") in https://github.com/eankeen/dots

	EOF
}

util_print_file() {
	echo "# Autogenerated from file. Do NOT edit!"
	echo "# --------------------------------------------------------------------------------"

	cat "$1"
}

# Ex.
# alias l='ls -al' # clone(user, root)
util_extract_alias() {
	sed -En "s/^(.*?) ?# ?clone ?(\(|.*?, )$1(\)|, ).*?$/# Autogenerated. Do NOT edit!\\n\1\\n/p"
}

# Ex.
# set convert-meta off # clone(user, root)
# util_extract_readline() {
# 	sed -En "s/^(.*?) ?# ?clone ?(\(|.*?, )$1(\)|, ).*?$/# Autogenerated. Do NOT edit!\\n\1\\n/p"
# }


# ----------------------- Variables ---------------------- #
: "${XDG_CONFIG_HOME:=$HOME/.config}"
generatedDir="$XDG_CONFIG_HOME/shell/generated"
currentDir="$XDG_CONFIG_HOME/shell/scripts"
profileDir="$XDG_CONFIG_HOME/shell"

# ------------------------- Main ------------------------- #
# user Functions
exec 6> "$generatedDir/.bashrc-user-functions.sh"
util_print_autogen_info >&6
find "$XDG_CONFIG_HOME/shell/modules/functions/" -ignore_readdir_race -type f -name "*.sh" \
		-exec sh -c "\"$currentDir/extractFunctions.pl\" 'user' < \"\$0\"" {} \; >&6
util_print_file "$profileDir/modules/util.sh" >&6
exec 6<&-

# user Aliases
exec 6> "$generatedDir/.bashrc-user-aliases.sh"
util_print_autogen_info >&6
find "$XDG_CONFIG_HOME/shell/modules/aliases/" -ignore_readdir_race -type f -name "*.sh" \
		-exec sh -c 'cat < $0' {} \; \
	| util_extract_alias 'user' >&6
util_print_file "$profileDir/modules/aliases/aliases.sh" >&6
exec 6<&-

# user Readline
exec 6> "$generatedDir/.bashrc-user-readline.sh"
util_print_file "$XDG_CONFIG_HOME/bash/modules/readline.sh" >&6
exec 6<&-



# root Functions
exec 6> "$generatedDir/.bashrc-root-functions.sh"
util_print_autogen_info >&6
find "$XDG_CONFIG_HOME/shell/modules/functions/" -ignore_readdir_race -type f -name "*.sh" \
		-exec sh -c "\"$currentDir/extractFunctions.pl\" 'root' < \"\$0\"" {} \; >&6
util_print_file "$profileDir/modules/util.sh" >&6
exec 6<&-

# root Aliases
exec 6> "$generatedDir/.bashrc-root-aliases.sh"
util_print_autogen_info >&6
find "$XDG_CONFIG_HOME/shell/modules/aliases/" -ignore_readdir_race -type f -name "*.sh" \
		-exec sh -c 'cat < $0' {} \; \
	| util_extract_alias 'root' >&6
util_print_file "$profileDir/modules/aliases/aliases.sh" >&6
exec 6<&-

# root Readline
exec 6> "$generatedDir/.bashrc-root-readline.sh"
util_print_file "$XDG_CONFIG_HOME/bash/modules/readline.sh" >&6
exec 6<&-
