[c]
name = "C"

[cpp]
name = "C++"

[git]
name = "Git"
tags = ["vcs"]

[github]
name = "GitHub"
include = ["git"]
overwrite = true
tags = ["vcs"]

[javascript]
name = "JavaScript"
include = ["core/editorconfig"]
tags = ["lang"]

[typescript]
name = "TypeScript"
include = ["core/editorconfig"]
tags = ["lang"]
