#!/usr/bin/env perl

my $input = do { local $/; <STDIN> };
while($input =~ /# root\n^(?<functionName>[^(]*?)\(\)(?<functionBody>(.|\n)*?^})/gum) {
        print <<"EOF";
# This function is autogenerated by $ENV{HOME}/scripts/generateRootFunctions.sh
$+{functionName}()$+{functionBody}\n
EOF
}
