#!/usr/bin/env bash

# functions
find "$XDG_CONFIG_HOME"/profile/fns{,-category}/ -ignore_readdir_race -type f -name "*.sh" \
		-exec sh -c '"$HOME/scripts/generateRootFunctions.pl" < "$0"' {} \; \
	| sudo tee "$HOME/.dots/system/root/.bashrc-generated-functions" >/dev/null

# aliases
exec 3<> >(sudo tee "$HOME/.dots/system/root/.bashrc-generated-aliases" >/dev/null)
>&3 echo -e "# This file is autogenerated by $HOME/scripts/generateRootbash.sh\n"
>&3 sed -En 's/(.*) # root/\1/p' < "$HOME/config/profile/aliases/misc.sh"; echo >&3
>&3 cat < "$XDG_CONFIG_HOME/profile/aliases/aliases.sh"
exec 3<&-
