# managed by 'eankeen/globe'; don't edit!

blank_issues_enabled: true
contact_links:
  - name: My Twitter
    url: https://twitter.com/EdwinKofler
  - name: My Website
    url: https://edwinkofler.com
