config:
  backup: true
  banner: false
  check_version: true
  create: true
  dotpath: '~/.dotfiles/os/unix/user'
  # import_configs:
  # - './dotfiles-home-decl.yaml'
  link_dotfile_default: 'relative'
  link_on_import: 'relative'
  template_dotfile_default: false
  workdir: '~/.dotfiles/.dotdrop-workdir'

dotfiles:
  f_agignore:
    src: .agignore
    dst: ~/.agignore
  f_alsoftrc:
    src: .alsoftrc
    dst: ~/.alsoftrc
  f_digrc:
    src: .digrc
    dst: ~/.digrc
  f_gnuplot:
    src: .gnuplot
    dst: ~/.gnuplot
  f_hushlogin:
    src: .hushlogin
    dst: ~/.hushlogin
  f_psqlrc:
    src: .psqlrc
    dst: ~/.psqlrc

  f_aerc_aerc:
    src: '.config/aerc/aerc.conf'
    dst: '{{@@ xdg_config_home @@}}/aerc/aerc.conf'

profiles:
  nullptr:
    variables:
      email: 'edwin@kofler.dev'
      home_src: '~/.dotfiles/os/unix/user'
      cfg_src: '~/.dotfiles/os/unix/user/.config'
      state_src: '~/.dotfiles/os/unix/user/.local/state'
      data_src: '~/.dotfiles/os/unix/user/.local/share'
    dynvariables:
      home_dst: 'printf "%s\n" "$HOME"'
      cfg_dst: 'printf "%s\n" "$XDG_CONFIG_HOME"'
      state_dst: 'printf "%s\n" "$XDG_STATE_HOME"'
      data_dst: 'printf "%s\n" "$XDG_DATA_HOME"'
    import:
      - './dotfiles-home-list.yaml'
