#!/usr/bin/env bash

for branch in $(git for-each-ref --format='%(refname:short)' --merged=HEAD refs/heads); do
	if [ "$branch" = 'master' ] || [ "$branch" = 'main' ]; then
		continue
	fi

	echo "$branch"
done
