[advice]
	addEmptyPathspec = false
[core]
	warnAmbiguousRefs = true ; default
	; pager = ; See ./diff.conf
[init]
	defaultBranch = main
[add "interactive"]
	useBuiltIn = true
[blame]
	coloring = highlightRecent
	date = relative
[apply]
	whitespace = warn
[branch]
	autoSetupMerge = true
[checkout]
	defaultRemote = me
[clone]
	defaultRemoteName = me
[clean]
	requireForce = true ; default
[color "blame"]
	highlightRecent = magenta,2 year ago,red,12 month ago,yellow,6 month ago,green,1 month ago,cyan
[color]
	diff = auto
	status = auto
	branch = auto
	pager = true ; default
[color "push"]
	error = magenta
[color "transport"]
	rejected = magenta
[color]
	ui = true
[commit]
	gpgSign = true
	template = ~/.home/xdg_config_dir/git/commit_template.txt
[include]
	path = include/diff.conf
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[gpg]
	; program = gpg ; default
	format = openpgp ; default
[help]
	autoCorrect = never
[merge]
	; conflictstyle = ; See ./diff.conf
	ff = true ; default
[pull]
	ff = true ; default
	rebase = false
[push]
	default = simple ; default
	followTags = true
[rerere]
	enabled = true
[rebase]
	stat = true
[status]
	showStash = true
	showUntrackedFiles = all
	submoduleSummary = true
[tag]
	forceSignAnnotated = true
	gpgSign = true
[user]
	name = Edwin Kofler
	email = edwin@kofler.dev
	signingkey = 0x650E7B05E22F31C5
[credential]
	credentialStore = secretservice

; Some less popular diff tools that may be useful later:
; - github.com/jeffkaufman/icdiff
; - github.com/benjamine/jsondiffpatch (json)
; - github.com/holman/spaceman-diff (images)
; - github.com/daveewart/colordiff (mostly redundant)
; - github.com/ymattw/ydiff (in dev)
; - github.com/mookid/diffr (in dev)

; Use a specialized diff tool.
[include]
	path = ./diff/diff-so-fancy.conf

# GitHub
[url "git@github.com:"]
	insteadOf = gh:
	pushInsteadOf = gh:
[url "git@github.com:hyperupcall/"]
	insteadOf = gh:hy:
	pushInsteadOf = gh:hy:
[url "git@github.com:hyperupcall-archives/"]
	insteadOf = gh:ha:
	pushInsteadOf = gh:ha:
[url "git@github.com:hyperupcall-projects/"]
	insteadOf = gh:hp:
	pushInsteadOf = gh:hp:

[url "git@github.com:bash-bastion/"]
	insteadOf = gh:bb:
	pushInsteadOf = gh:bb:
[url "git@github.com:version-manager/"]
	insteadOf = gh:vm:
	pushInsteadOf = gh:vm:

# GitLab
[url "git@gitlab.com:"]
	insteadOf = gl:
	pushInsteadOf = gl:
[url "git@gitlab.com:hyperupcall/"]
	insteadOf = gl:hy:
	pushInsteadOf = gl:hy:
