""" standard
set tabstop=4
set softtabstop=0
set expandtab
set shiftwidth=2
set smarttab
set nocp

""" vim-plug
" specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
" - also requires these three settings to be turned on
set nocompatible
filetype plugin on
syntax on
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-sensible'
Plug 'vimwiki/vimwiki'
call plug#end()


""" nerd tree
" open nerdtree when vim starts up on opening a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif
" close vim if only window left if nerdtree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" map C-n to toggling nerd tree window
map <C-n> :NERDTreeToggle<CR>
" close vim if the only winodw left open is nerd tree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" show dotfiles in nerdtree
let NERDTreeShowHidden=1
" ensure that vim does not open files and other buffers in the nerd tree window
autocmd BufEnter * if bufname('#') =~# "^NERD_tree_" && winnr('$') > 1 | b# | endif
" change default arrows
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1

" cycling throug hidden buffers
:nnoremap <C-n> :bnext<CR>
:nnoremap <C-p> :bprevious<CR>
