#!/usr/bin/env bash
set -ETeo pipefail

source ./util/core.sh

declare -a optionalCliDotFiles=(
	"$home/.alsoftrc"
	"$home/.config/conky"
	"$home/.config/wtf"
	"$home/.cpan/CPAN/MyConfig.pm"
	"$home/.hushlogin"
	# "$home/.pam_environment"
	"$home/.yarnrc"
	"$cfg/albert/albert.conf"
	"$cfg/albert-sticker-search"
	"$cfg/alsa"
	"$cfg/appimagelauncher.cfg"
	"$cfg/broot"
	"$cfg/cabal/config"
	"$cfg/calcurse"
	"$cfg/cargo"
	"$cfg/cava"
	"$cfg/ccache"
	"$cfg/chezmoi"
	"$cfg/choose"
	"$cfg/cmus/rc"
	"$cfg/conda"
	"$cfg/curl"
	"$cfg/ddcutil"
	"$cfg/emptty"
	"$cfg/fontconfig"
	"$cfg/gdb"
	"$cfg/osc"
	"$cfg/hg"
	"$cfg/htop"
	"$cfg/ion"
	"$cfg/irb"
	"$cfg/irssi"
	"$cfg/lazydocker"
	"$cfg/libfsguest"
	"$cfg/liquidprompt"
	"$cfg/llpp.conf"
	"$cfg/ly"
	"$cfg/maven"
	"$cfg/most"
	"$cfg/mpd"
	"$cfg/mpv"
	"$cfg/nb"
	"$cfg/ncpamixer.conf"
	"$cfg/neofetch"
	"$cfg/nimble"
	"$cfg/npm"
	"$cfg/nu"
	"$cfg/nvchecker"
	"$cfg/ox"
	"$cfg/pacman"
	"$cfg/pacmixer"
	"$cfg/pamix.conf"
	"$cfg/paru"
	"$cfg/pavucontrol.ini"
	"$cfg/pijul"
	"$cfg/please"
	"$cfg/pudb"
	"$cfg/pulse/client.conf"
	"$cfg/pulsemixer.cfg"
	"$cfg/pypoetry"
	"$cfg/python"
	"$cfg/ranger"
	"$cfg/ripgrep"
	"$cfg/rtorrent"
	"$cfg/salamis"
	"$cfg/slack-term"
	"$cfg/systemd"
	"$cfg/taskwarrior"
	"$cfg/tig"
	"$cfg/tilda"
	"$cfg/tmux"
	"$cfg/toast"
	"$cfg/todotxt"
	"$cfg/user-dirs.dirs"
	"$cfg/wget"
	"$cfg/wtf"
	"$cfg/yay"
	"$cfg/youtube-dl"
	"$data/gnupg/gpg.conf"
	"$data/gnupg/dirmngr.conf"
	"$data/sdkman/etc/config"
)

printArray 'optionalCliDotFiles'

