title: "Edwin's dotfiles"
description: "Edwin's personal dotfiles."
baseurl: ''
url: ''

markdown: kramdown
theme: minima
permalink: /:basename:output_ext
github_username: hyperupcall
linkedin_username: edwinkofler

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-relative-links
- jekyll-optional-front-matter

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
- Gemfile
- Gemfile.lock
- vendor/
- .bundle/
