[alias]
a = "add"
b = "build"
br = "build --release"
brr = "build --release"
r = "run"
rr = "run --release"
c = "check"
f = "fmt"
t = "test"
pp = "clippy"
clr = "clean"
upd = "update"
trp = "tarpaulin -o Xml -v"
d = "doc"
i = "install"
o = "outdated -Rv"

[net]
# git-fetch-with-cli = true

[build]
# rustc-wrapper = "sccache"
