# GitHub
[url "git@github.com:"]
	insteadOf = gh:
	pushInsteadOf = gh:
[url "git@github.com:hyperupcall/"]
	insteadOf = gh:hy:
	pushInsteadOf = gh:hy:
[url "git@github.com:hyperupcall-archives/"]
	insteadOf = gh:ha:
	pushInsteadOf = gh:ha:
[url "git@github.com:hyperupcall-projects/"]
	insteadOf = gh:hp:
	pushInsteadOf = gh:hp:

[url "git@github.com:bash-bastion/"]
	insteadOf = gh:bb:
	pushInsteadOf = gh:bb:
[url "git@github.com:version-manager/"]
	insteadOf = gh:vm:
	pushInsteadOf = gh:vm:

# GitLab
[url "git@gitlab.com:"]
	insteadOf = gl:
	pushInsteadOf = gl:
[url "git@gitlab.com:hyperupcall/"]
	insteadOf = gl:hy:
	pushInsteadOf = gl:hy:
