; Some less popular diff tools that may be useful later:
; - github.com/jeffkaufman/icdiff
; - github.com/benjamine/jsondiffpatch (json)
; - github.com/holman/spaceman-diff (images)
; - github.com/daveewart/colordiff (mostly redundant)
; - github.com/ymattw/ydiff (in dev)
; - github.com/mookid/diffr (in dev)

; Use a specialized diff tool.
[include]
	path = diff/diff-so-fancy.conf

; Common
[diff "gpg"]
	textconv = gpg --no-tty --decrypt
[diff "pandoc2md"]
	textconv = pandoc --to=markdown
[diff "pdfconf"]
	textconv = pdftohtml -stdout
[diff "wrap"]
	textconv = fmt
[diff "exif"]
	textconv = exiftool
[diff "mp3"]
	textconv = mp3info -x
[diff "xlsconf"]
	textconv = xls2csv
[diff "zipshow"]
	textconv = unzip -c -a
[diff "unzip -l"]
	textconv = unzip -l
;[diff "spaceman-diff"]
;	command = spaceman-diff
[difftool]
	prompt = false ; difftastic recommendation
[difftool "difftastic"]
	cmd = difft "$LOCAL" "$REMOTE"
[pager]
	difftool = true
