#!/usr/bin/env sh

: "${XDG_STATE_HOME:?}"
: "${XDG_CONFIG_HOME:?}"

# Ensure logs
logFile="$XDG_STATE_HOME/X11/xinitrc.log"
[ -f "$logFile" ] || {
	mkdir -p "$XDG_STATE_HOME/X11"
	touch "$logFile"
	chmod 600 "$logFile"
} 2>/dev/null >&2
exec >> "$logFile" 2>&1
printf "\033[1m------ INFO: X session started for %s at %s ------\033[0m\n" "$(id -un)" "$(date)"

# Source system
[ -d /etc/X11/xinit/xinitrc.d ] && {
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
}

[ -d /etc/X11/Xsession.d ] && {
	for f in /etc/X11/Xsession.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
}

# Apply settings and start apps
. "$XDG_CONFIG_HOME/X11/settings.sh"
systemctl --user start xorg.target

exec defaultmgr launch window-manager
