map icb cd ~/.home/xdg_config_dir/bash
map icc cd ~/.home/xdg_config_dir
map icg cd ~/.home/xdg_config_dir/git
map icn cd ~/.home/xdg_config_dir/neovim
map icr cd ~/.home/xdg_config_dir/ranger
map ics cd ~/.home/xdg_config_dir/sh

map ida cd ~/.home/xdg_data_dir/applications
map idt cd ~/.home/xdg_data_dir/Trash
map idp cd ~/.home/xdg_data_dir/password-store

map ihc cd ~/.home/Documents
map ihd cd ~/.home/Documents
map ihb cd ~/.home/Public
map ihh cd ~
map ihk cd ~/.home/Desktop
map ihm cd ~/.home/Music
map ihp cd ~/.home/Pictures
map ihs cd ~/scripts
map iht cd ~/.home/Templates
map ihv cd ~/.home/Videos
map ihw cd ~/.home/Downloads
map ihx cd ~/Dropbox

map im cd /run/media
map is cd ~/Dropbox/School

map nd console mkdir%space
map nf console touch%space
map nr console rename%space

map cr console rename%space

# map r eval fm.source(fm.confpath('rc.conf'))
# map r eval fm.rifle.reload_config()
