name: 'Update Website Blacklist'

on:
  schedule:
    - cron: '0 1 */7 * *'
  workflow_dispatch:

jobs:
  update-and-commit:
    environment: 'otternaut'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'

      - name: 'Setup Deno'
        uses: 'denoland/setup-deno@v2'
        with:
          deno-version: 'v2.x'

      - run: './scripts/compile-blacklist.ts'

      - name: 'Commit'
        run: |
          GPG_TTY=$(tty) gpg --batch --yes --pinentry-mode loopback --passphrase-file <(cat <<< '${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}') --import <<< "${{ secrets.GPG_PRIVATE_KEY }}"
          git add config/ublacklist-compiled.txt
          git add config/ublockorigin-compiled.txt
          git \
            -c user.name='Otternaut' \
            -c user.email='99463792+otternaut-bot@users.noreply.github.com' \
            commit \
            --author='Otternaut <99463792+otternaut-bot@users.noreply.github.com>' \
            -S0xFB6C155AFD89739C \
            -m '$(date "+%Y.%m.%d")'
          git push
