name: 'Update Website Denylist'

on:
  schedule:
    - cron: '0 1 */7 * *'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}'
  cancel-in-progress: true

permissions: {}

jobs:
  update-and-commit:
    environment: 'otternaut'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd' # v6.0.2
        with:
          persist-credentials: false

      - name: 'Setup Deno'
        uses: 'denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282' # v2.0.4
        with:
          deno-version: 'v2.x'

      - run: './lscripts/compile-blacklist.ts'

      - uses: 'crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd' # v7.0.0
        with:
          gpg_private_key: '${{ secrets.GPG_PRIVATE_KEY }}'
          passphrase: '${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}'

      - name: 'Commit'
        permissions:
          contents: 'write'
        run: |
          _date=$(date '+%Y-%m-%d')
          git add config/ublacklist-compiled.txt
          git add config/ublockorigin-compiled.txt
          git \
            -c user.name='Otternaut' \
            -c user.email='99463792+otternaut-bot@users.noreply.github.com' \
            commit \
            -m "$_date" \
            --author='Otternaut <99463792+otternaut-bot@users.noreply.github.com>' \
            -S0xFB6C155AFD89739C
          git push
