name: 'Update Website Blacklist'

on:
  schedule:
    - cron: '0 1 */7 * *'
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'

      - name: 'Setup Deno'
        uses: 'denoland/setup-deno@v2'
        with:
          deno-version: 'v2.x'

      - run: './scripts/compile-blacklist.ts'

      - name: 'Set COMMIT_MESSAGE'
        run: echo "COMMIT_MESSAGE=$(date '+%Y.%m.%d')" >> $GITHUB_ENV

      - uses: 'EndBug/add-and-commit@v9'
        with:
          author_name: 'Otternaut'
          author_email: '99463792+otternaut-bot@users.noreply.github.com'
          message: '${{ env.COMMIT_MESSAGE }}'
